jenkins:
    url: http://127.0.0.1:8081/
    job: /job/vrp-simple
    buildTrigger: /build

vrpRunner:
    vrpPath: /home/lubiedak/workspace/VRPFinalRepo/VRP/Release/VRPCore2.0
    workspaceDir: /home/lubiedak/workspace/workspaceVRP/
    fileName: input

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/vrpdb
        username: root
        password: 
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: validate
            