jenkins:
    url: http://127.0.0.1:8081/
    job: /job/vrp-simple
    buildTrigger: /build

vrpRunner:
    vrpPath: /home/lubiedak/workspace/VRPFinalRepo/VRP/Release/VRPCore2.0

spring:
    data:
        mongodb.host: 127.0.0.1
        mongodb.port: 27017
        mongodb.uri: mongodb://127.0.0.1/test
        mongo.repositories.enabled: true
            